name: Build Blog On Push

on: 
  push: 
    branches: [ main ] 

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
       - uses: actions/checkout@v2
       - name: Build Blog
         run: bash ./blog
